[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/en/index.html"
  to = "/en/"
  status = 301

[dev]
  command = ""
  port = 8888
