[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/en/index.html"
  to = "/en/"
  status = 301

[[redirects]]
  from = "/es/index.html"
  to = "/es/"
  status = 301

[[redirects]]
  from = "/fr/index.html"
  to = "/fr/"
  status = 301

[[redirects]]
  from = "/de/index.html"
  to = "/de/"
  status = 301

[dev]
  command = ""
  port = 8888
